### ISSUE TITLE
ScratchX OpenWeather extension no longer works

### ISSUE THREAD

**Issue by SteveJSmythe** [savaka2/scratch-extensions#18]
Hello
I have tried the Scratch team's OpenWeather extension but it doesn't work. I think one issue is that, since October 2015, an API key is needed to get access to the data. I also suspect that the data field parsing in the Javascript is no longer working but I don't know enough to see where the problem lies.

**Comment by savaka2** [comment]
It seems you posted this on the wrong repository. If you are referring to [this extension](http://scratchx.org/?url=https://cdn.rawgit.com/sayamindu/scratch-extensions/master/weather_extension.js#scratch) then you should make an issue at https://github.com/sayamindu/scratch-extensions.

**Comment by SteveJSmythe** [comment]
Sorry, but I don't seem to have access to make issues for that repository

**Comment by savaka2** [comment]
Oh he turned off issues. You could contact him by email or some other method

**Comment by SteveJSmythe** [comment]
OK. Thanks. Sorry to confuse!

Steve

On 9 March 2016 at 12:31, Sam <notifications@github.com> wrote:

> Oh he turned off issues. You could contact him by email or some other
> method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/savaka2/scratch-extensions/issues/18#issuecomment-194274603>
> .
>



-- 
See also:

Steve Smythe Consulting <http://www.smythe-consulting.co.uk>
